//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.11.18 at 01:57:36 PM MSK 
//


package com.example.eximporter.exporter.model.xml.project;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import java.util.List;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="admediumPage" maxOccurs="unbounded" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;attribute name="pageTechId" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                 &lt;attribute name="pageKey" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                 &lt;attribute name="workPageNum" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                 &lt;attribute name="admediumVersionId" type="{http://www.w3.org/2001/XMLSchema}string" />
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *       &lt;attribute name="exportSequenceId" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "admediumPage", "admediumPageDeleted"
})
@XmlRootElement(name = "admediumPageExport")
public class AdmediumPageExport {

    protected List<AdmediumPage> admediumPage;

    protected List<AdmediumPageDeleted> admediumPageDeleted;

    public List<AdmediumPage> getAdmediumPage() {
        return admediumPage;
    }

    public void setAdmediumPage(List<AdmediumPage> admediumPage) {
        this.admediumPage = admediumPage;
    }

    public List<AdmediumPageDeleted> getAdmediumPageDeleted() {
        return admediumPageDeleted;
    }

    public void setAdmediumPageDeleted(List<AdmediumPageDeleted> admediumPageDeleted) {
        this.admediumPageDeleted = admediumPageDeleted;
    }
}
