//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2017.11.18 at 01:57:36 PM MSK
//
package com.example.eximporter.exporter.model.xml.project;

/**
 * <p>
 * Java class for anonymous complex type.
 * <p>
 * The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;attribute name="pageTechId" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="pageKey" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="workPageNum" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="admediumVersionId" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 */
public abstract class BasePage {

    public abstract String getPageTechId();
    public void setPageTechId(String pageTechId) {}

}
