//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.11.16 at 01:05:52 PM MSK 
//


package com.example.eximporter.exporter.model.xml.peo;

import javax.xml.bind.annotation.*;
import java.util.ArrayList;
import java.util.List;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="placement" maxOccurs="unbounded" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="placementSku" maxOccurs="unbounded" minOccurs="0">
 *                     &lt;complexType>
 *                       &lt;simpleContent>
 *                         &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
 *                           &lt;attribute name="skuTechId" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                           &lt;attribute name="countryIsoCode" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                           &lt;attribute name="advertisedPrice" type="{http://www.w3.org/2001/XMLSchema}float" />
 *                           &lt;attribute name="markDownPrice" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                           &lt;attribute name="priceReductionRoundedDown" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                           &lt;attribute name="priceReduction5PercRounded" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                           &lt;attribute name="advertisedPriceDeletedIndicator" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                         &lt;/extension>
 *                       &lt;/simpleContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *                 &lt;attribute name="placementTechId" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                 &lt;attribute name="articleTechId" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                 &lt;attribute name="orderNumber" type="{http://www.w3.org/2001/XMLSchema}int" />
 *                 &lt;attribute name="pageKey" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                 &lt;attribute name="position" type="{http://www.w3.org/2001/XMLSchema}byte" />
 *                 &lt;attribute name="pageSlice" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                 &lt;attribute name="hasFabricSampleIndicator" type="{http://www.w3.org/2001/XMLSchema}string" />
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *       &lt;attribute name="exportSequenceId" type="{http://www.w3.org/2001/XMLSchema}short" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "placement", "placementDeleted"
})
@XmlRootElement(name = "omnPlacementExport")
public class OmnPlacementExport {

    protected List<Placement> placement;
    protected List<PlacementDeleted> placementDeleted;

    public void setPlacement(List<Placement> placement) {
        this.placement = placement;
    }

    public List<PlacementDeleted> getPlacementDeleted() {
        return placementDeleted;
    }

    public void setPlacementDeleted(List<PlacementDeleted> placementDeleted) {
        this.placementDeleted = placementDeleted;
    }

    public List<Placement> getPlacement() {
        if (placement == null) {
            placement = new ArrayList<>();
        }
        return this.placement;
    }
}
